### ISSUE TITLE
odoh_rs::ObliviousDoHMessagePlaintext::new panicked at 'capacity overflow', and memory allocation failure.

### ISSUE THREAD

**Issue by WIZeaz** [cloudflare/odoh-rs#30]
Hi, I am fuzzing this crate with afl.rs, and I found several panics. I list the reproductive code snippets below. The version I test is 1.0.2.

This case panicked at 'capacity overflow'
```rust
    let _local0 = <std::vec::Vec::<u8, std::alloc::Global> as std::convert::From::<&str>>::from("0");
    let _local1: odoh_rs::ObliviousDoHMessagePlaintext = odoh_rs::ObliviousDoHMessagePlaintext::new(_local0, 17625665026532540416);
    let _ = odoh_rs::ObliviousDoHMessagePlaintext::into_msg(_local1);
```
panic information:
```
thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: alloc::raw_vec::capacity_overflow
   3: alloc::raw_vec::RawVec<T,A>::allocate_in
             at /home/jjf/Fuzzing-Target-Generator/library/alloc/src/raw_vec.rs:178:27
   4: alloc::raw_vec::RawVec<T,A>::with_capacity_zeroed_in
             at /home/jjf/Fuzzing-Target-Generator/library/alloc/src/raw_vec.rs:139:9
   5: <u8 as alloc::vec::spec_from_elem::SpecFromElem>::from_elem
             at /home/jjf/Fuzzing-Target-Generator/library/alloc/src/vec/spec_from_elem.rs:52:31
   6: alloc::vec::from_elem
             at /home/jjf/Fuzzing-Target-Generator/library/alloc/src/vec/mod.rs:2566:5
   7: odoh_rs::protocol::ObliviousDoHMessagePlaintext::new
             at ./src/protocol.rs:422:22
   8: replay_odoh_rs0::test_function0
             at ./fuzz_target/build/replay_odoh_rs0/src/main.rs:45:58
   9: replay_odoh_rs0::main
             at ./fuzz_target/build/replay_odoh_rs0/src/main.rs:79:5
  10: core::ops::function::FnOnce::call_once
             at /home/jjf/Fuzzing-Target-Generator/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The same case with different input may cause a memory allocation failure.
```rust
    let _local0 = <std::vec::Vec::<u8, std::alloc::Global> as std::convert::From::<&str>>::from("0");
    let _local1: odoh_rs::ObliviousDoHMessagePlaintext = odoh_rs::ObliviousDoHMessagePlaintext::new(_local0, 3617290116880544306);
    let _ = odoh_rs::ObliviousDoHMessagePlaintext::into_msg(_local1);
```
This case shows an memory allocation failure and crash.
```
memory allocation of 3617290116880544306 bytes failed
```

**Comment by xofyarg** [comment]
Hi,

Thanks for raising this issue. As you commented above, the memory ran out when allocating for padding, because the given input was too big. For the client, I believe it's caller's responsibility to decide the proper padding size. Then the padding length will be stored as a 16 bits, so I don't think it will be an issue on the server side.
